### ISSUE TITLE
Adding 1-3 items to the minecraft loot table + with configs

### ISSUE THREAD

**Issue by SnowShock35** [SnowShock35/Golden-Treasures#13]
Up to you what items they're (Could add config for all if u wanted) and yeah add them as a low chance to spawn in dungeon loot (dungeon loot being any of the types that they're are (dungeon, village blacksmith, etc.)

**Comment by LyraelRayne** [comment]
I created some generic items (they're just called "ingredient 1, ingredient 2, etc.) with copies of other items' icons for now. Will need some artwork and clever names :P

Working on making them spawn in dungeon loot now.

**Comment by LyraelRayne** [comment]
Done!

**Comment by LyraelRayne** [comment]
Hmm I suspect I misread this one as being making random items to be used for crafting. Now I'm thinking that you meant that players should be able to occasionally find the items from the mod in the chests. Which is a good idea and I shall implement that now!

**Comment by LyraelRayne** [comment]
Done again!
